// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace HelloMixpanel
{
	public partial class SomeTableViewController : UIViewController
	{
		public SomeTableViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
