// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace HelloMixpanel
{
	public partial class TopNavViewController : UINavigationController
	{
		public TopNavViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
